services:
  mysql-db:
    image: mysql:8.0
    container_name: payment-gateway-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: payment_gateway
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    container_name: payment-gateway-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PAYMENT_AUTHORIZER_URL: ${PAYMENT_AUTHORIZER_URL}
    depends_on:
      mysql-db:
        condition: service_healthy
volumes:
  mysql-data: